server:
  # 端口
  port: 8083
redis:
  host: 192.168.4.3:6379
  password: 123456
spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  # 邮箱
  mail:
    # 邮箱发送服务器地址
#    host: smtp.qq.com
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: UTF-8
    # 发送者的邮箱地址
    username: m13781858837@163.com
    # 授权码(在邮箱开通时获取)
    password: xxxxxxxxxxxxS
    # 端口号 (不同邮箱端口号不同)
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true

  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: admin
    # 密码
    password: admin
    # 服务器地址
    host: 192.168.4.3
    virtual-host: /
    # 端口
    port: 5672
    # 交换机开启确认消息
    publisher-confirm-type: correlated
    # 开启消息不可路由,回退消息给生产者
    publisher-returns: true
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: WJHwjh20010825.
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
